# Generated by Django 5.0.1 on 2024-01-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
