# Generated by Django 5.0.1 on 2024-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0002_alter_appointment_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_time',
            field=models.IntegerField(choices=[(0, '07:30 – 10:30'), (1, '13:00 – 16:30'), (3, '18:30 – 09:30')]),
        ),
    ]
