# Generated by Django 5.0.1 on 2024-02-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0002_rename_department_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='doctor',
            new_name='employee',
        ),
    ]
