# Generated by Django 5.0.1 on 2024-02-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0003_rename_doctor_schedule_employee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient', 'department', 'booking_date', 'booking_time')},
        ),
    ]
