# Generated by Django 5.0.1 on 2024-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
