# Generated by Django 5.0.1 on 2024-02-03 08:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0005_user_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Employee',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
