# Generated by Django 5.0.1 on 2024-02-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0006_prescription_prescriptionmedicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='healthclinic.appointment', unique=True),
        ),
    ]
