# Generated by Django 5.0.1 on 2024-02-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0007_alter_prescription_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicine',
            new_name='medicine_list',
        ),
    ]
