# Generated by Django 5.0.1 on 2024-02-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0008_rename_medicine_prescription_medicine_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicine_list',
            new_name='medicine',
        ),
    ]
