# Generated by Django 5.0.1 on 2024-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0011_prescription_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
