# Generated by Django 5.0.1 on 2024-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclinic', '0012_prescriptionmedicine_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
